### ISSUE TITLE
Hill Slope doesn't produce valid output

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/rapid-watershed-delineation#18]
http://localhost:5000/rwd/-75.276639/39.692986?snapping=0

Will not produce geoJSON

```
No JSON object could be decoded
Traceback (most recent call last):
  File "/opt/rwd/src/api/main.py", line 70, in run_rwd
    output = json.load(output_json_file)
  File "/usr/local/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by kdeloach** [comment]
This works now (note that we switched lat/lng in the URL query):

```
vagrant@worker:~$ curl http://localhost:5000/rwd/39.692986/-75.276639?snapping=0
{
  "input_pt": {
    "features": [
      {
        "geometry": {
          "coordinates": [
            -75.276639,
            39.692986
          ],
          "type": "Point"
        },
        "properties": {
          "ID": 1,
          "Lat": 39.692986,
          "Lon": -75.276639
        },
        "type": "Feature"
      }
    ],
    "type": "FeatureCollection"
  },
  "watershed": {
    "features": [
      {
        "geometry": {
          "coordinates": [
            [
              [
                -75.27666666666865,
                39.693055555586305
              ],
              [
                -75.27657407407585,
                39.693055555586305
              ],
              [
                -75.27657407407585,
                39.69296296299361
              ],
              [
                -75.27666666666865,
                39.69296296299361
              ],
              [
                -75.27666666666865,
                39.693055555586305
              ]
            ]
          ],
          "type": "Polygon"
        },
        "properties": {
          "Area": 8.0855e-05,
          "AvgOLF": 0.0,
          "Avgslp": 0.221630781888962,
          "BR": 0.0,
          "BasinLen": 0.0,
          "DrnDen": -405268.69086636574,
          "GRIDCODE": 1,
          "RR": NaN,
          "StrLen": -32.768,
          "Strord": -32768.0
        },
        "type": "Feature"
      }
    ],
    "type": "FeatureCollection"
  }
}
```
